### ISSUE TITLE
Missing "Pending Tasks" CSS style

### ISSUE THREAD

**Issue by gihyunlee** [SpecialOperations/Dark-Mode-for-Google-Calendar#1]
Thanks for creating this 'dark mode' style for Google Calendar, only my 2nd day using it and loving it.

Just wanted to report you may have missed the style for "pending tasks"

Here is a screenshot where I have "7 pending tasks" and I am using your dark mode style.:
<img width="642" alt="Screenshot_20221110_112102" src="https://user-images.githubusercontent.com/347389/201178111-ec107a8c-9ac4-4c5b-a048-761b03e728be.png">

Here is a screenshot without any styles applied:
<img width="545" alt="Screenshot_20221110_112526" src="https://user-images.githubusercontent.com/347389/201178248-1ee20679-8e20-427d-ac5d-f7d2e590cd03.png">

Would be awesome to also style the pending tasks "button" element in the calendar so that it is a muted color similar to calendar events in the past.

Thanks!

**Comment by SpecialOperations** [comment]
Thanks, this has been fixed in the latest update.
