### ISSUE TITLE
Styling not applied to header

### ISSUE THREAD

**Issue by mihaelbabic** [SpecialOperations/Dark-Mode-for-Google-Calendar#2]
Hi,

Thanks for creating this. Longterm real eye saver. Everything works really well except that styles are not being applied to my header for some reason.

![screencapture-calendar-google-calendar-u-0-r-2022-11-30-13_43_39](https://user-images.githubusercontent.com/72862332/204800792-edf56dea-dc6a-4556-ae9c-b480599866ca.png)

![image](https://user-images.githubusercontent.com/72862332/204800804-428db2ac-2558-492d-b9dd-e8c238a0cb20.png)

It would really mean a lot if You can get it fixed.
Thanks in advance :)

**Comment by SpecialOperations** [comment]
Thanks for bringing it up, this has been fixed in the latest release. You can manually update by clicking "Check all styles for updates" in the Stylus extension settings. 
![image](https://user-images.githubusercontent.com/30572191/204866085-a45b4966-105c-4088-81c8-1bb564fdf2c0.png)
