### ISSUE TITLE
`contacts.google.com` not working properly

### ISSUE THREAD

**Issue by AucaCoyan** [SpecialOperations/Dark-Mode-for-Google-Calendar#4]
Hello! I really like this OLED theme, I found it's currently the best in my opinion for Google Calendar.
Wandering around I found that it also applies to `contacts`, but when I turned on I saw this:

![image](https://github.com/SpecialOperations/Dark-Mode-for-Google-Calendar/assets/30557287/4d9f520c-023f-4147-8dfb-5d701e421daf)

Is it possible to remove `contacts` from de regex expression until it's done?

Thanks and great work! keep it comin'

**Comment by SpecialOperations** [comment]
Hi, thanks for your patience. This issue, as well as various other bugs, has been fixed in the latest release. Be sure to go to your Stylus settings and press "Check all styles for updates" and the new update should become available to install.
